### ISSUE TITLE
json: cannot unmarshal string into Go struct field Level.Levels.BGColor of type color.Color

### ISSUE THREAD

**Issue by darltrash** [SolarLune/ldtkgo#1]
I was trying to load a regular ldtk 0.6.1 file and i got this error :(

Go Version: go1.15.5 linux/amd64
OS: Void Linux Musl
Arch: x86_64

[LDTK map file here](https://github.com/SolarLune/ldtkgo/files/5756492/origin.zip)

**Comment by SolarLune** [comment]
OK, that should resolve the issue. Thanks for reporting!

**Comment by darltrash** [comment]
Sorry for late response, Now it works fine, Thank you!

**Comment by SolarLune** [comment]
No, no problem. Glad to hear it's fixed!
