### ISSUE TITLE
nil pointer dereference when calling PropertyByIdentifier with non-existing key

### ISSUE THREAD

**Issue by TLINDEN** [SolarLune/ldtkgo#10]
When you call `PropertyByIdentifier` with a non-existing key, like so:
```go
[..]
system.Print(system.Plan.PropertyByIdentifier("Description").AsString(), 10, 470)
[..]
```
then you get this:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7b8564]

goroutine 34 [running]:
github.com/solarlune/ldtkgo.(*Property).AsString(...)
        /home/scip/go/pkg/mod/github.com/solarlune/ldtkgo@v0.9.4-0.20240310011150-66aa15c2ab56/ldtkgo.go:54
openquell/systems.(*HudSystem).Draw(0xc0007ce4e0, 0xa4b2f8?)
        /home/scip/dev/openquell/systems/hud_system.go:56 +0x384
```

Although this was entirely my own fault, I think it would be better to get a proper error message here from the library.

Nevertheless - thanks A LOT for this library, already love it!

best,
Tom ("Bad Kraut")

**Comment by SolarLune** [comment]
Hello, and thank you very much for using ldtkgo! I appreciate your report, as well.

I think I see what you mean, but the problem with returning an error as well as the property is that now you have to assign the result to two fields and you can't plug the function into another like you're doing here, even if you know the property exists.

If the function were to panic instead, it could print a custom error, but then it wouldn't be easy to detect if a property exists or not and continue execution.

**Comment by TLINDEN** [comment]
Yeah, I see your point, that would be annoying as well.

My current workaround is to do a sanity check at compilation time:
```go
        // do some sanity checks
        properties := []string{"minmoves", "background", "level", "description"}
        need := len(properties)

        for idx, level := range project.Levels {
                have := 0

                for _, property := range level.Properties {
                        if util.Contains(properties, property.Identifier) {
                                have++
                        }
                }

                if have != need {
                        log.Fatalf("level definition for level %d (%s) invalid: %d missing properties\n   required: %s",
                                idx, level.Identifier, need-have, strings.Join(properties, ", "),
                        )
                }
        }
```

maybe not the most efficient way to do it, but since it's only being executed once at build time, it's good enough for me :)

The downside of this method is, that every level needs to have every propertiy, even if not needed.

**Comment by SolarLune** [comment]
Yeah, it's definitely something that you need to think about and weigh the pros and cons of. I think, overall, though, the existing PropertyByIdentifier function works OK for this purpose. I'll close this issue now~
